version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
